codecov:
  notify:
    slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project: yes
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no